// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview An AI agent that recommends a daily calorie and macronutrient intake based on user data and fitness goals.
 *
 * - getCalorieRecommendation - A function that handles the calorie and macro recommendation process.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const CalorieRecommendationInputSchema = z.object({
  age: z.number().describe('La edad del usuario.'),
  weight: z.number().describe('El peso del usuario en kilogramos.'),
  height: z.number().describe('La altura del usuario en centímetros.'),
  activityLevel: z
    .enum(['sedentary', 'lightlyActive', 'moderatelyActive', 'veryActive', 'extraActive'])
    .describe('El nivel de actividad del usuario.'),
  goal: z.enum(['loseWeight', 'maintainWeight', 'gainMuscle']).describe('El objetivo de fitness del usuario.'),
});
export type CalorieRecommendationInput = z.infer<typeof CalorieRecommendationInputSchema>;

const CalorieRecommendationOutputSchema = z.object({
  recommendedCalories: z.number().describe('La ingesta diaria de calorías recomendada.'),
  recommendedProtein: z.number().describe('La ingesta diaria de proteínas recomendada en gramos.'),
  recommendedCarbs: z.number().describe('La ingesta diaria de carbohidratos recomendada en gramos.'),
  recommendedFats: z.number().describe('La ingesta diaria de grasas recomendada en gramos.'),
  explanation: z.string().describe('Una explicación detallada de cómo se calcularon las recomendaciones de calorías y macronutrientes.'),
});
export type CalorieRecommendationOutput = z.infer<typeof CalorieRecommendationOutputSchema>;

export async function getCalorieRecommendation(input: CalorieRecommendationInput): Promise<CalorieRecommendationOutput> {
  return calorieRecommendationFlow(input);
}

const prompt = ai.definePrompt({
  name: 'calorieRecommendationPrompt',
  input: {schema: CalorieRecommendationInputSchema},
  output: {schema: CalorieRecommendationOutputSchema},
  prompt: `Eres un entrenador personal que recomienda una ingesta diaria de calorías y macronutrientes basada en los datos personales y objetivos de fitness del usuario.

  Calcula la ingesta diaria de calorías recomendada y el desglose de macronutrientes (proteínas, carbohidratos, grasas) en gramos basándote en la siguiente información:
  Edad: {{{age}}}
  Peso: {{{weight}}} kg
  Altura: {{{height}}} cm
  Nivel de Actividad: {{{activityLevel}}}
  Objetivo: {{{goal}}}

  Proporciona una explicación detallada de cómo calculaste las recomendaciones de calorías y macronutrientes y por qué es apropiado para el objetivo del usuario.
  Asegúrate de que la explicación sea fácil de entender y proporcione consejos prácticos.

  Devuelve el resultado en formato JSON.
  `,
});

const calorieRecommendationFlow = ai.defineFlow(
  {
    name: 'calorieRecommendationFlow',
    inputSchema: CalorieRecommendationInputSchema,
    outputSchema: CalorieRecommendationOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
