
// This is an autogenerated file from Firebase Studio.
// https://firebase.google.com/docs/web/setup#available-libraries

import {initializeApp, getApp, getApps} from 'firebase/app';
import {getFirestore} from 'firebase/firestore';
import { getAuth } from "firebase/auth";

// Your web app's Firebase configuration
// ❗️ PASTE YOUR FIREBASE CONFIGURATION HERE
const firebaseConfig = {
  apiKey: "AIzaSyAoqx3KBZd59k64fkrmFZUExv0_oSmSFOA",
  authDomain: "nutritrack-vb9op.firebaseapp.com",
  projectId: "nutritrack-vb9op",
  storageBucket: "nutritrack-vb9op.firebasestorage.app",
  messagingSenderId: "207242465394",
  appId: "1:207242465394:web:c40cae0fc534f9e36672eb"
};

// Initialize Firebase
const app = getApps().length > 0 ? getApp() : initializeApp(firebaseConfig);
const db = getFirestore(app);
const auth = getAuth(app);

export {db, auth};
